"""Stable typed taxonomy for the isolated Strategy 2 domain."""

from enum import Enum


class PositionState(str, Enum):
    CANDIDATE = "CANDIDATE"
    ARMED = "ARMED"
    PENDING = "PENDING"
    OPEN_RISK = "OPEN_RISK"
    BREAK_EVEN = "BREAK_EVEN"
    PROFIT_PROTECTED = "PROFIT_PROTECTED"
    CLOSED = "CLOSED"
    INVALIDATED = "INVALIDATED"
    CANCELLED = "CANCELLED"
    DATA_STALE = "DATA_STALE"


class DecisionStatus(str, Enum):
    NO_ENTRY = "NO_ENTRY"
    ENTER = "ENTER"
    HOLD = "HOLD"
    EXIT = "EXIT"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class ReasonCode(str, Enum):
    NO_ENTRY = "NO_ENTRY"
    ENTER_CANDIDATE = "ENTER_CANDIDATE"
    SHADOW_SKIPPED = "SHADOW_SKIPPED"
    REPLAY = "REPLAY"
    INVALID_SNAPSHOT = "INVALID_SNAPSHOT"
    DATA_STALE = "DATA_STALE"
    FEATURE_INCOMPLETE = "FEATURE_INCOMPLETE"
    TREND_NOT_HEALTHY = "TREND_NOT_HEALTHY"
    PULLBACK_NOT_ARMED = "PULLBACK_NOT_ARMED"
    RECOVERY_UNCONFIRMED = "RECOVERY_UNCONFIRMED"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    LIQUIDITY_INSUFFICIENT = "LIQUIDITY_INSUFFICIENT"
    NET_EDGE_NON_POSITIVE = "NET_EDGE_NON_POSITIVE"
    FILL_MISSED = "FILL_MISSED"
    RISK_REJECTED = "RISK_REJECTED"
    HARD_INVALIDATION = "HARD_INVALIDATION"
    PROTECTIVE_STOP = "PROTECTIVE_STOP"
    BREAK_EVEN = "BREAK_EVEN"
    TRAILING_PROFIT = "TRAILING_PROFIT"
    NET_TARGET = "NET_TARGET"
    MAX_HOLD_REEVALUATION = "MAX_HOLD_REEVALUATION"
    CANCELLED = "CANCELLED"
    ENTRY_APPROVED = "ENTRY_APPROVED"
    HOLDING = "HOLDING"


TERMINAL_POSITION_STATES = frozenset(
    {
        PositionState.CLOSED,
        PositionState.INVALIDATED,
        PositionState.CANCELLED,
        PositionState.DATA_STALE,
    }
)
