"""Pure domain contracts for AutoTrade Replacement."""

from .candidate import (
    CandidateCaptureError,
    CandidateEligibility,
    CandidateProvenance,
    CandidateProvenanceV2,
    CandidateSourceV2,
    CandidateSnapshot,
    CandidateTrigger,
    CandidateUse,
    ClockRead,
    EligibilityReason,
    RngRef,
    RuntimeManifestRef,
    SourceCursor,
    StableRef,
    capture_candidate,
    capture_candidate_v2,
    derive_revision_token,
    revise_candidate,
)
from .content import ContentRecipe, ContentRef, content_ref_v1, content_ref_v2
from .encoding import CANONICAL_ENCODING_VERSION, CanonicalEncodingError, canonical_bytes
from .decision import (
    CanonicalDecision, CommitStatus, DecisionAction, DecisionBoundary,
    DecisionCommitResult, DecisionError, DecisionReason, DecisionReasonCode, IntegrityIncident,
    PositionContext, PositionState, commit_decision, evaluate_decision,
)
from .identity import DeterministicIdentity, IdentityError, build_identity, identity_preimage
from .execution import (
    AccountState, DispatchEnvelope, ExecutionError, ExecutionIntent, ExecutionOrder,
    ExecutionPreparation, ExecutionSide, OrderSettlementState, OutboxMessage,
    OutboxStatus, SettlementEntry, SettlementResult, prepare_execution, settle_event,
)
from .errors import CapabilityRegistryError, MarketEvidenceError, RecoveryEvaluationError
from .market import (
    AffectedScope, AuthScope, AuthoritativeFieldEvidence, CapabilityArtifact,
    CapabilityEntry, CapabilityLookup, CapabilityRegistry, ContinuityResult,
    CursorCapability, EvidenceAdmission, EvidenceDisposition, EvidencePolicy,
    EvidenceRequirement, EvidenceRequirementSet, FreezeRequest, MarketEvidence,
    ProductFamily, QualificationReason, QualificationStatus, RateLimitContract,
    RateLimitStatus,
    ReconciliationCheckpoint, ReconciliationRequest, RecoveryContract,
    RecoveryDisposition, RecoveryGateResult, RecoveryMode, RecoveryProof,
    RecoveryRequest, ScopeKind, ScopedClearRequest, TimestampContract,
    TimestampUnit, evaluate_recovery_gate,
)
from .accounting import CashLedgerEntry, MovementType, PositionAccount
from .calibration import (
    CalibrationContext, CalibrationError, CalibrationMetric, CalibrationPoint,
    CalibrationTolerance, CalibrationVerdict, EvidenceAuthority, EvidenceLabel,
    ExecutionCalibrationReport,
)
from .exit_protection import (
    DustIncident, ExitDecision, ExitError, ExitEvaluation, ExitEvaluator,
    ExitFillResult, ExitReason, ExitSignals, PositionProtectionState,
    PositionProtectionStatus, ProtectionState, apply_exit_fill,
    build_exit_execution, evaluate_exit, exit_command_ref,
)
from .fencing import FencedWriterAuthority, FencedWriterLease
from .portfolio_allocation import (
    AllocationProposal, AllocationRejectCode, AllocationRejection, AppliedFill,
    ConstituentCheckpoint, PortfolioAllocation, PortfolioConsistencyCut,
    ReservationBucket, ReservationConsumption, ReservationLifecycle,
    ReservationVector, RiskReservation, build_portfolio_allocation,
)
from .risk_governor import (
    AdjustmentKind, CanonicalEquitySnapshot, EntryRiskRequest,
    QuantityAdjustment, RiskCheckReason, RiskEvaluationResult, RiskGovernor,
    RiskPolicy, RiskPortfolioState,
)
from .safety_state import (
    ClearPredicate, ProtectiveAction, SafetyCause, SafetyCauseKind,
    SafetyClearProof, SafetyClearRecord, SafetyScope, SafetyScopeLevel,
    SafetySeverity, SafetyStateLattice,
)
from .kill_switch import KillState, KillSwitchStateMachine
from .degradation import DegradationGovernor, DegradationLevel
from .experiment import EvidenceSpecification
from .policy_isolation import PolicyExecutionFrame, PolicyRole
from .trial_ledger import MaturedOutcomeTaxonomy, TrialLedgerEntry
from .comparison import CommonComparisonResult
from .evidence_report import SealedEvidenceReport
from .promotion import PolicyAuthorityState, PolicyPromotionRecord
from .legacy_inventory import LegacyEntityDisposition, LegacyInventoryClassifier, LegacyInventoryRecord
from .runtime_artifact import QualifiedRuntimeManifest
from .migration_gate import MigrationVerificationResult
from .fact_import import ApprovedExternalFact
from .cutover import CutoverState, CutoverStep
from .rollback_retention import AdditiveRollbackRecord
from .recovery import (
    CorrectionKind, CorrectionRequest, LifecycleRecoveryManager,
    ProjectionHighWater, RecoveryAction, RecoveryCheckpoint, RecoveryError,
    RecoveryPlan, RecoveryState, VenueOrderEvidence, plan_recovery,
)
from .numeric import ScaledInteger
from .simulator import (
    CostRules, FeeType, LifecycleAction, LifecycleActionType, LifecycleResult,
    LifecycleScenario, OrderSimulator, OrderStatus, ScenarioOutcome, SimulatedFill,
    SimulatorError, SimulatorEvent, reduce_lifecycle,
)
from .policy import (
    CalibrationEvidence,
    CalibrationStatus,
    GapBehavior,
    GrossReturnEvidence,
    PolicyEvaluationError,
    PolicyState,
    PolicyTransition,
    ShortfallComponent,
    ShortfallComponentEvidence,
    ShortfallEvidence,
    build_margin_ref,
    evaluate_policy_transition,
)
from .replay import (
    DecisionReplayBundle,
    ReplayComparison,
    ReplayError,
    ReplayManifest,
    ReplayMode,
    ReplayObservability,
    ReplayResult,
    SemanticDiff,
    SemanticProjectionProfile,
    clock_read_ref,
    compare_replay_results,
    policy_state_ref,
    regenerate_replay,
    semantic_hash,
    semantic_projection,
    source_cursor_ref,
    stable_ref_key,
)

__all__ = (
    "AdjustmentKind",
    "AllocationProposal",
    "AllocationRejectCode",
    "AllocationRejection",
    "AppliedFill",
    "CANONICAL_ENCODING_VERSION",
    "CandidateCaptureError",
    "CandidateEligibility",
    "CandidateProvenance",
    "CandidateProvenanceV2",
    "CandidateSourceV2",
    "CandidateSnapshot",
    "CandidateTrigger",
    "CandidateUse",
    "CalibrationContext",
    "CalibrationError",
    "CalibrationMetric",
    "CalibrationPoint",
    "CalibrationTolerance",
    "CalibrationVerdict",
    "CapabilityArtifact",
    "CapabilityEntry",
    "CapabilityLookup",
    "CapabilityRegistry",
    "CapabilityRegistryError",
    "CalibrationEvidence",
    "CalibrationStatus",
    "CanonicalEncodingError",
    "CanonicalDecision",
    "CanonicalEquitySnapshot",
    "CostRules",
    "CommitStatus",
    "ConstituentCheckpoint",
    "ContentRecipe",
    "ContentRef",
    "ContinuityResult",
    "CursorCapability",
    "DecisionAction",
    "DecisionBoundary",
    "DecisionCommitResult",
    "DecisionError",
    "DecisionReason",
    "DecisionReasonCode",
    "DecisionReplayBundle",
    "DeterministicIdentity",
    "EligibilityReason",
    "EntryRiskRequest",
    "EvidenceAdmission",
    "EvidenceAuthority",
    "EvidenceLabel",
    "EvidenceDisposition",
    "EvidencePolicy",
    "EvidenceRequirement",
    "EvidenceRequirementSet",
    "ExecutionCalibrationReport",
    "ExecutionError",
    "ExecutionIntent",
    "ExecutionOrder",
    "ExecutionPreparation",
    "ExecutionSide",
    "ExitError",
    "ExitDecision",
    "ExitEvaluation",
    "ExitEvaluator",
    "ExitFillResult",
    "ExitReason",
    "ExitSignals",
    "FeeType",
    "FreezeRequest",
    "GapBehavior",
    "GrossReturnEvidence",
    "MarketEvidence",
    "MarketEvidenceError",
    "LifecycleAction",
    "LifecycleActionType",
    "LifecycleResult",
    "LifecycleScenario",
    "OrderSimulator",
    "OrderStatus",
    "OrderSettlementState",
    "OutboxMessage",
    "OutboxStatus",
    "RngRef",
    "IdentityError",
    "IntegrityIncident",
    "PositionContext",
    "PositionState",
    "PositionProtectionState",
    "PositionProtectionStatus",
    "ProtectionState",
    "ProductFamily",
    "QualificationReason",
    "QualificationStatus",
    "QuantityAdjustment",
    "PolicyEvaluationError",
    "PolicyState",
    "PolicyTransition",
    "PortfolioAllocation",
    "PortfolioConsistencyCut",
    "ReplayComparison",
    "ReplayError",
    "ReplayManifest",
    "ReplayMode",
    "ReplayObservability",
    "ReplayResult",
    "RecoveryContract",
    "RecoveryCheckpoint",
    "RecoveryDisposition",
    "RecoveryEvaluationError",
    "RecoveryError",
    "RecoveryGateResult",
    "RecoveryMode",
    "RecoveryProof",
    "RecoveryRequest",
    "ReservationBucket",
    "ReservationConsumption",
    "ReservationLifecycle",
    "ReservationVector",
    "RiskReservation",
    "RiskCheckReason",
    "RiskEvaluationResult",
    "RiskGovernor",
    "RiskPolicy",
    "RiskPortfolioState",
    "RecoveryPlan",
    "RecoveryAction",
    "RecoveryState",
    "LifecycleRecoveryManager",
    "ReconciliationCheckpoint",
    "ReconciliationRequest",
    "ScaledInteger",
    "SettlementEntry",
    "SettlementResult",
    "ScenarioOutcome",
    "SimulatedFill",
    "SimulatorError",
    "SimulatorEvent",
    "ScopeKind",
    "ScopedClearRequest",
    "ClockRead",
    "RuntimeManifestRef",
    "SourceCursor",
    "StableRef",
    "AffectedScope",
    "AccountState",
    "CorrectionKind",
    "CorrectionRequest",
    "ProjectionHighWater",
    "VenueOrderEvidence",
    "build_portfolio_allocation",
    "DustIncident",
    "AuthScope",
    "AuthoritativeFieldEvidence",
    "ShortfallComponent",
    "ShortfallComponentEvidence",
    "ShortfallEvidence",
    "RateLimitContract",
    "RateLimitStatus",
    "SemanticDiff",
    "SemanticProjectionProfile",
    "build_identity",
    "build_margin_ref",
    "canonical_bytes",
    "clock_read_ref",
    "identity_preimage",
    "prepare_execution",
    "plan_recovery",
    "apply_exit_fill",
    "build_exit_execution",
    "evaluate_exit",
    "exit_command_ref",
    "policy_state_ref",
    "capture_candidate",
    "capture_candidate_v2",
    "commit_decision",
    "compare_replay_results",
    "content_ref_v1",
    "content_ref_v2",
    "derive_revision_token",
    "evaluate_decision",
    "evaluate_policy_transition",
    "evaluate_recovery_gate",
    "regenerate_replay",
    "reduce_lifecycle",
    "settle_event",
    "revise_candidate",
    "semantic_hash",
    "semantic_projection",
    "source_cursor_ref",
    "stable_ref_key",
    "TimestampContract",
    "TimestampUnit",
    "DispatchEnvelope",
)
