"""Pure domain contracts for AutoTrade Replacement."""

from .candidate import (
    CandidateCaptureError,
    CandidateEligibility,
    CandidateProvenance,
    CandidateProvenanceV2,
    CandidateSourceV2,
    CandidateSnapshot,
    CandidateTrigger,
    CandidateUse,
    ClockRead,
    EligibilityReason,
    RngRef,
    RuntimeManifestRef,
    SourceCursor,
    StableRef,
    capture_candidate,
    capture_candidate_v2,
    derive_revision_token,
    revise_candidate,
)
from .content import ContentRecipe, ContentRef, content_ref_v1, content_ref_v2
from .encoding import CANONICAL_ENCODING_VERSION, CanonicalEncodingError, canonical_bytes
from .decision import (
    CanonicalDecision, CommitStatus, DecisionAction, DecisionBoundary,
    DecisionCommitResult, DecisionError, DecisionReason, DecisionReasonCode, IntegrityIncident,
    PositionContext, PositionState, commit_decision, evaluate_decision,
)
from .identity import DeterministicIdentity, IdentityError, build_identity, identity_preimage
from .errors import CapabilityRegistryError, MarketEvidenceError, RecoveryEvaluationError
from .market import (
    AffectedScope, AuthScope, AuthoritativeFieldEvidence, CapabilityArtifact,
    CapabilityEntry, CapabilityLookup, CapabilityRegistry, ContinuityResult,
    CursorCapability, EvidenceAdmission, EvidenceDisposition, EvidencePolicy,
    EvidenceRequirement, EvidenceRequirementSet, FreezeRequest, MarketEvidence,
    ProductFamily, QualificationReason, QualificationStatus, RateLimitContract,
    RateLimitStatus,
    ReconciliationCheckpoint, ReconciliationRequest, RecoveryContract,
    RecoveryDisposition, RecoveryGateResult, RecoveryMode, RecoveryProof,
    RecoveryRequest, ScopeKind, ScopedClearRequest, TimestampContract,
    TimestampUnit, evaluate_recovery_gate,
)
from .accounting import CashLedgerEntry, MovementType, PositionAccount
from .calibration import ExecutionCalibrationReport
from .exit_protection import ExitDecision, ExitEvaluator, ExitReason, ProtectionState
from .fencing import FencedWriterAuthority, FencedWriterLease
from .portfolio_allocation import PortfolioAllocation, RiskReservation
from .risk_governor import RiskCheckReason, RiskEvaluationResult, RiskGovernor
from .safety_state import SafetyCause, SafetyCauseKind, SafetyScopeLevel, SafetyStateLattice
from .kill_switch import KillState, KillSwitchStateMachine
from .recovery import LifecycleRecoveryManager, RecoveryAction, RecoveryState
from .numeric import ScaledInteger
from .simulator import FeeType, OrderSimulator, OrderStatus, SimulatedFill, SimulatorEvent
from .policy import (
    CalibrationEvidence,
    CalibrationStatus,
    GapBehavior,
    GrossReturnEvidence,
    PolicyEvaluationError,
    PolicyState,
    PolicyTransition,
    ShortfallComponent,
    ShortfallComponentEvidence,
    ShortfallEvidence,
    build_margin_ref,
    evaluate_policy_transition,
)
from .replay import (
    DecisionReplayBundle,
    ReplayComparison,
    ReplayError,
    ReplayManifest,
    ReplayMode,
    ReplayObservability,
    ReplayResult,
    SemanticDiff,
    SemanticProjectionProfile,
    clock_read_ref,
    compare_replay_results,
    policy_state_ref,
    regenerate_replay,
    semantic_hash,
    semantic_projection,
    source_cursor_ref,
    stable_ref_key,
)

__all__ = (
    "CANONICAL_ENCODING_VERSION",
    "CandidateCaptureError",
    "CandidateEligibility",
    "CandidateProvenance",
    "CandidateProvenanceV2",
    "CandidateSourceV2",
    "CandidateSnapshot",
    "CandidateTrigger",
    "CandidateUse",
    "CapabilityArtifact",
    "CapabilityEntry",
    "CapabilityLookup",
    "CapabilityRegistry",
    "CapabilityRegistryError",
    "CalibrationEvidence",
    "CalibrationStatus",
    "CanonicalEncodingError",
    "CanonicalDecision",
    "CommitStatus",
    "ContentRecipe",
    "ContentRef",
    "ContinuityResult",
    "CursorCapability",
    "DecisionAction",
    "DecisionBoundary",
    "DecisionCommitResult",
    "DecisionError",
    "DecisionReason",
    "DecisionReasonCode",
    "DecisionReplayBundle",
    "DeterministicIdentity",
    "EligibilityReason",
    "EvidenceAdmission",
    "EvidenceDisposition",
    "EvidencePolicy",
    "EvidenceRequirement",
    "EvidenceRequirementSet",
    "FreezeRequest",
    "GapBehavior",
    "GrossReturnEvidence",
    "MarketEvidence",
    "MarketEvidenceError",
    "RngRef",
    "IdentityError",
    "IntegrityIncident",
    "PositionContext",
    "PositionState",
    "ProductFamily",
    "QualificationReason",
    "QualificationStatus",
    "PolicyEvaluationError",
    "PolicyState",
    "PolicyTransition",
    "ReplayComparison",
    "ReplayError",
    "ReplayManifest",
    "ReplayMode",
    "ReplayObservability",
    "ReplayResult",
    "RecoveryContract",
    "RecoveryDisposition",
    "RecoveryEvaluationError",
    "RecoveryGateResult",
    "RecoveryMode",
    "RecoveryProof",
    "RecoveryRequest",
    "ReconciliationCheckpoint",
    "ReconciliationRequest",
    "ScaledInteger",
    "ScopeKind",
    "ScopedClearRequest",
    "ClockRead",
    "RuntimeManifestRef",
    "SourceCursor",
    "StableRef",
    "AffectedScope",
    "AuthScope",
    "AuthoritativeFieldEvidence",
    "ShortfallComponent",
    "ShortfallComponentEvidence",
    "ShortfallEvidence",
    "RateLimitContract",
    "RateLimitStatus",
    "SemanticDiff",
    "SemanticProjectionProfile",
    "build_identity",
    "build_margin_ref",
    "canonical_bytes",
    "clock_read_ref",
    "identity_preimage",
    "policy_state_ref",
    "capture_candidate",
    "capture_candidate_v2",
    "commit_decision",
    "compare_replay_results",
    "content_ref_v1",
    "content_ref_v2",
    "derive_revision_token",
    "evaluate_decision",
    "evaluate_policy_transition",
    "evaluate_recovery_gate",
    "regenerate_replay",
    "revise_candidate",
    "semantic_hash",
    "semantic_projection",
    "source_cursor_ref",
    "stable_ref_key",
    "TimestampContract",
    "TimestampUnit",
)
